name: unicorn-binance-trailing-stop-loss

channels:
  - conda-forge

dependencies:
  - python>=3.9
  - Cython
  - requests
  - unicorn-binance-rest-api>=2.2.0
  - unicorn-binance-websocket-api>=2.13.0
